# Generated by Django 4.0.3 on 2022-03-31 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the genre', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the star', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(help_text='IMDB film ID', max_length=12, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='The English title of the film', max_length=100)),
                ('year', models.SmallIntegerField(help_text='The year of release')),
                ('runtime', models.SmallIntegerField(blank=True, help_text='Runtime in minutes', null=True)),
                ('plot', models.TextField(blank=True, help_text='The year of release')),
                ('content_rating', models.CharField(blank=True, help_text='The MPAA rating of the film', max_length=8)),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='movies.genre')),
                ('stars', models.ManyToManyField(blank=True, related_name='movies', to='movies.star')),
            ],
        ),
    ]
